{% set name = "requests-toolbelt" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/requests-toolbelt-{{ version }}.tar.gz
  sha256: 7681a0a3d047012b5bdc0ee37d7f8f07ebe76ab08caeccfc3921ce23c88d5bc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.0.1,<3.0.0

test:
  imports:
    - requests_toolbelt
    - requests_toolbelt.adapters
    - requests_toolbelt.auth
    - requests_toolbelt.downloadutils
    - requests_toolbelt.multipart
    - requests_toolbelt.threaded
    - requests_toolbelt.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://toolbelt.readthedocs.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A utility belt for advanced users of python-requests.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - sigmavirus24
